name: cicada
description: "Client for cicada."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  audio_service: ^0.18.18
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  get_it: ^8.2.0
  just_audio: ^0.10.4
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
